[leafs]
leaf1 ansible_host=192.168.100.201
leaf2 ansible_host=192.168.100.202
leaf3 ansible_host=192.168.100.203

[spines]
spine1 ansible_host=192.168.100.101
spine2 ansible_host=192.168.100.102

[leafs:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=arista.eos.eos
ansible_user=admin
ansible_password=admin
ansible_become=true
ansible_become_method=enable
ansible_become_password=admin
ansible_ssh_type=libssh

[spines:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=arista.eos.eos
ansible_user=admin
ansible_password=admin
ansible_become=true
ansible_become_method=enable
ansible_become_password=admin
