---
hostname: leaf1
bgp_as: 65001
bgp_router_id: 10.1.1.1
loopback0: 10.1.1.1/32
management_ip: 192.168.100.201/24

uplinks:
  - name: Ethernet2
    description: TO-SPINE1-Eth1
    ip: 10.0.1.2/30
  - name: Ethernet3
    description: TO-SPINE2-Eth1
    ip: 10.0.2.2/30

bgp_neighbors:
  - ip: 10.0.1.1
    remote_as: 65100
  - ip: 10.0.2.1
    remote_as: 65100

host_ports:
  - name: Ethernet1
    description: ACCESS-BACHELIERS
    mode: access
    vlan: 10

leaf_vlans: [10, 20]
border_leaf: false
default_route: false
