---
hostname: spine2
bgp_router_id: 10.1.0.2
loopback0: 10.1.0.2/32
management_ip: 192.168.100.102/24

uplinks:
  - name: Ethernet1
    description: TO-LEAF1-Eth3
    ip: 10.0.2.1/30
  - name: Ethernet2
    description: TO-LEAF2-Eth2
    ip: 10.0.2.5/30
  - name: Ethernet3
    description: TO-LEAF3-Eth2
    ip: 10.0.2.9/30

bgp_neighbors:
  - ip: 10.0.2.2
    remote_as: 65001
  - ip: 10.0.2.6
    remote_as: 65002
  - ip: 10.0.2.10
    remote_as: 65000
